apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-a-to-httpbin
  namespace: test-app
spec:
  hosts:
    - httpbin.org
    - www.httpbin.org
  http:
    - match:
        - port: 80
          sourceLabels:
            k8s-app: app-a
      route:
        - destination:
            host: egress-httpbin.external.svc.cluster.local
            port:
              number: 80
