apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-b-to-google
  namespace: test-app
spec:
  hosts:
    - google.com
    - www.google.com
  http:
    - match:
        - port: 80
          sourceLabels:
            k8s-app: app-b
      route:
        - destination:
            host: egress-google.external.svc.cluster.local
            port:
              number: 80
