apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-a-to-cnn
  namespace: test-app
spec:
  hosts:
    - cnn.com
    - www.cnn.com
  http:
    - match:
        - port: 80
          sourceLabels:
            k8s-app: app-a
      route:
        - destination:
            host: egress-cnn.external.svc.cluster.local
            port:
              number: 80
