apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-external
  namespace: external
spec:
  hosts:
    - httpbin.org
    - www.httpbin.org
  ports:
    - number: 80
      name: http
      protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
  exportTo:
  - "."
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-egress
  namespace: external
spec:
  hosts:
    - httpbin.org
    - www.httpbin.org
  gateways:
    - external/egress-httpbin
  http:
    - match:
        - gateways:
            - external/egress-httpbin
          port: 80
      route:
        - destination:
            host: httpbin.org
            port:
              number: 80
